[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "py-solc-x>=2.0.4",
    "python-dotenv>=1.1.1",
    "reportlab>=4.4.3",
    "sqlalchemy>=2.0.43",
    "twilio>=9.7.2",
    "web3>=7.13.0",
    "werkzeug>=3.1.3",
]
